export const GENRES = [
  'Salone Mix',
  'Afrobeats',
  'Amapiano',
  'Reggae',
  'Dancehall',
  'Palm Wine / Cultural',
  'Hip-Hop / Rap',
  'R&B / Soul',
  'Gospel / Praise',
  'Highlife / Coupe Decale',
  'Soukous / Makossa',
  'Soca / Calypso',
  'Club & Party Mixes',
  'Wedding & Event Essentials',
  'Old Skool / Throwbacks',
  'House / Electronic / EDM',
  'Afro-House / Deep House',
  'Trap & Drill',
  'Afro-Fusion / Afro-Pop',
];
